# Unpublish from npm if Github Release is deleted or hidden.
# Requires: `NPM_TOKEN` as secret

name: npm:unpublish
on:
  release:
    types:
      - deleted
      - unpublished
jobs:
  npm-unpublish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: npm unpublish <package>@<version>
        run: |
          version=$(echo "$TAG_NAME" | sed 's/[^0-9.]*//g')
          name="$(npm pkg get name | tr -d '"')"

          npm unpublish $name@$version
        env: 
          TAG_NAME: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
